---
- name: yum install go-agent
  become: yes
  yum: pkg=go-agent-{{ GOCD_GO_VERSION }} state=installed
  when: ansible_pkg_mgr=='yum'

- name: apt install go-agent
  become: yes
  apt: pkg=go-agent={{ GOCD_GO_VERSION }} state=present force=yes
  when: ansible_pkg_mgr=='apt'
  # notify:
  # - restart go-agent

- name: Create additional agents setup script.
  become: yes
  template:
    src: go-agents-setup-sh
    dest: /var/tmp/go-agents-setup.sh
    mode: 0755
    owner: root
    group: root

- debug: msg="{{ ansible_processor_count }} CPUs with {{ ansible_processor_cores }} cores detected.  {{ GOCD_AGENT_INSTANCES }} agents will be installed."

- name: Run script to setup multiple agents on the server
  command:
    cmd: /var/tmp/go-agents-setup.sh
    creates: /usr/share/go-agent-1/bin/go-agent
