---
- include: go-common.yml
- name: yum install go-server
  yum: pkg=go-server-{{go_version}} state=present
  notify:
  - restart go-server
  when: ansible_pkg_mgr=='yum'

- name: apt install go-server
  sudo: yes
  apt: pkg=go-server={{go_version}} state=present force=yes
  when: ansible_pkg_mgr=='apt'
  notify:
  - restart go-server

- name: start go-server
  service: name=go-server state=started
  notify:
     - ensure go-server running

# These won't work if you don't have firewalld, but they won't error out either
- name: enable Go HTTP traffic through firewalld
  firewalld: port=8153 permanent=true state=enabled

- name: enable Go HTTPS traffic through firewalld
  firewalld: port=8154/tcp permanent=true state=enabled
