---
- name: yum install go-server
  sudo: yes
  yum: pkg=go-server-{{ GOCD_GO_VERSION }} state=present
  notify:
  - restart go-server
  when: ansible_pkg_mgr=='yum'

- name: apt install go-server
  sudo: yes
  apt: pkg=go-server={{ GOCD_GO_VERSION }} state=present force=yes
  when: ansible_pkg_mgr=='apt'
  notify:
  - restart go-server

- name: start go-server
  sudo: yes
  service: name=go-server state=started
  notify:
     - ensure go-server running

- name: check if firewalld is available
  command: which firewalld
  ignore_errors: true
  register: firewalld

- name: enable Go HTTP traffic through firewalld
  sudo: yes
  firewalld: port=8153/tcp permanent=true state=enabled
  when: firewalld|success

- name: enable Go HTTPS traffic through firewalld
  sudo: yes
  firewalld: port=8154/tcp permanent=true state=enabled
  when: firewalld|success

- name: check if UFW is available
  command: which ufw
  ignore_errors: true
  register: ufw

- name: enable Go HTTP traffic through ufw
  sudo: yes 
  ufw: rule=allow port=8153 proto=tcp
  when: ufw|success
 
- name: enable Go HTTPS traffic through ufw
  sudo: yes
  ufw: rule=allow port=8154 proto=tcp
  when: ufw|success
