---
- include: go-common.yml
- name: install go-server, rh edition
  yum: pkg=go-server-{{go_version}} state=latest
  notify:
  - restart go-server
  when: ansible_pkg_mgr=='yum'

- name: install go-server, deb edition.
  sudo: yes
  apt: pkg=go-server={{go_version}} state=present force=yes
  when: ansible_pkg_mgr=='apt'
  notify:
  - restart go-server

- name: start go-server
  service: name=go-server state=started
  notify:
     - ensure go-server running
