---
- name: yum install go-server
  sudo: yes
  yum: pkg=go-server-{{ GOCD_GO_VERSION }} state=present
  notify:
  - restart go-server
  when: ansible_pkg_mgr=='yum'

- name: Check port 8153 is open
  sudo: no
  delegate_to: localhost
  uri: url=http://localhost:8153 return_content=yes
  register: gocd_firstpage
  

# - set_fact: html_version_token="{{ '('.join(GOCD_GO_VERSION.split('-')) }}"

# - name: Validate the version of Go installed
#   assert: { that: "{{ html_version_token }} in {{ gocd_firstpage.content }}" }

- name: Check that we're prompted to add a pipeline
  assert: { that: "'Add Pipeline - Go'.encode('ascii') in {{ gocd_firstpage.content.encode('ascii','ignore') }}" }

- name: Retrieve gocd config
  delegate_to: localhost
  sudo: no
  uri: url=http://localhost:8153/go/api/admin/config.xml return_content=yes dest="./config.xml"
  register: gocd_config
  
- shell: grep 'agent hostname=' config.xml|wc -l
  delegate_to: localhost
  sudo: no
  register: agent_count

- name: Ensure {{ GOCD_AGENT_INSTANCES }} agents registered
  assert: { that: "{{ agent_count.stdout.encode('ascii','ignore').strip() }} == {{ GOCD_AGENT_INSTANCES }}"}

