---
- name: yum install go-server
  become: yes
  yum: pkg=go-server-{{ GOCD_GO_VERSION }} state=present
  notify:
  - restart go-server
  when: ansible_pkg_mgr=='yum'

- name: apt install go-server
  become: yes
  apt: pkg=go-server={{ GOCD_GO_VERSION }} state=present force=yes
  when: ansible_pkg_mgr=='apt'

- name: flag that we're configuration a Go server
  set_fact: tmp_gocd_onserver=True

- name: replace /etc/default/go-server from package
  template: "src=go-server-defaults dest=/etc/default/go-server mode=0644 group={{ GOCD_GROUP }} owner={{ GOCD_USER }}"
  become: yes
  notify:
  - restart go-server

- name: start go-server
  become: yes
  service:
    name: go-server
    state: started
  notify:
     - ensure go-server running
