---

- name: Download install GOCD Plugins
  get_url: url="{{ item }}" dest="{{ GOCD_SERVER_PLUGIN }}"
  sudo_user: "{{ GOCD_USER }}"
  with_items: GOCD_PLUGINS_INSTALL
  notify:
   - restart go-server

- name: Remove GOCD  Plugins
  file: path="{{ GOCD_SERVER_PLUGIN }}/{{ item | basename }}" state=absent
  with_items: GOCD_PLUGINS_REMOVE
  sudo: yes
  notify:
   - restart go-server